//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.Server.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessage
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public int SenderID { get; set; }
        public int ReceiverID { get; set; }
    
        public virtual Account Receiver { get; set; }
        public virtual Account Sender { get; set; }
    }
}
