//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network.Server.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verification
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public System.DateTime ExpireDate { get; set; }
    }
}
